In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from google_config import google_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Poum,NC,2021-10-27 04:26:12,-20.2333,164.0167,76.10,70,100,5.88
1,1,Zhangye,CN,2021-10-27 04:26:12,38.9342,100.4517,50.14,40,0,2.93
2,2,Severo-Kurilsk,RU,2021-10-27 04:26:12,50.6789,156.1250,45.48,89,100,6.87
3,3,Saldanha,ZA,2021-10-27 04:26:13,-33.0117,17.9442,63.63,68,55,6.69
4,4,Kaitangata,NZ,2021-10-27 04:26:13,-46.2817,169.8464,54.79,83,73,4.99

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=google_key)

In [4]:
a = 33
b = 200
if b > a:
  print("b is greater than a")

b is greater than a

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
winds = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=winds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [25]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Poum,NC,2021-10-27 04:26:12,-20.2333,164.0167,76.10,70,100,5.88
10,10,Belmonte,BR,2021-10-27 04:26:15,-15.8631,-38.8828,77.50,84,3,7.65
13,13,The Valley,AI,2021-10-27 04:26:16,18.2170,-63.0578,82.26,70,0,10.65
15,15,Sibu,MY,2021-10-27 04:26:17,2.3000,111.8167,89.91,70,40,3.44
26,26,Ugoofaaru,MV,2021-10-27 04:26:20,5.6667,73.0000,80.98,76,100,5.84
31,31,Mahebourg,MU,2021-10-27 04:26:22,-20.4081,57.7000,77.29,65,20,13.80
33,33,Agua Verde,MX,2021-10-27 04:26:25,22.9000,-106.0500,83.12,83,8,4.90
35,35,Kapaa,US,2021-10-27 04:26:26,22.0752,-159.3190,80.58,85,1,8.05
36,36,Vaini,TO,2021-10-27 04:26:26,-21.2000,-175.2000,77.16,83,20,13.80
39,39,Hobart,AU,2021-10-27 04:21:55,-42.8794,147.3294,75.02,53,20,1.99

In [26]:
preferred_cities_df.count()

City_ID       161
City          161
Country       161
Date          161
Lat           161
Lng           161
Max Temp      161
Humidity      161
Cloudiness    161
Wind Speed    161
dtype: int64

In [27]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

# for the challenge you'll probably have to dropna the hotel column

          City Country  Max Temp      Lat       Lng Hotel Name
0         Poum      NC     76.10 -20.2333  164.0167
10    Belmonte      BR     77.50 -15.8631  -38.8828
13  The Valley      AI     82.26  18.2170  -63.0578
15        Sibu      MY     89.91   2.3000  111.8167
26   Ugoofaaru      MV     80.98   5.6667   73.0000
31   Mahebourg      MU     77.29 -20.4081   57.7000
33  Agua Verde      MX     83.12  22.9000 -106.0500
35       Kapaa      US     80.58  22.0752 -159.3190
36       Vaini      TO     77.16 -21.2000 -175.2000
39      Hobart      AU     75.02 -42.8794  147.3294

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

KeyboardInterrupt:

In [41]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {"location": f"{lat},{lng}", "radius": 5000, "types": "lodging", "key": google_key,}

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [42]:
hotel_df.head(40)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Poum,NC,76.10,-20.2333,164.0167,Gîte kajeon
10,Belmonte,BR,77.50,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
13,The Valley,AI,82.26,18.2170,-63.0578,CeBlue Villas & Beach Resort
15,Sibu,MY,89.91,2.3000,111.8167,RH HOTEL (4 Star)
26,Ugoofaaru,MV,80.98,5.6667,73.0000,Ungoofaaru Inn
31,Mahebourg,MU,77.29,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
33,Agua Verde,MX,83.12,22.9000,-106.0500,
35,Kapaa,US,80.58,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
36,Vaini,TO,77.16,-21.2000,-175.2000,Keleti Beach Resort
39,Hobart,AU,75.02,-42.8794,147.3294,Mantra on Collins Hobart
40,Kidal,ML,81.48,18.4411,1.4078,
43,Matara,LK,78.98,5.9485,80.5353,Amaloh Boutique Resort
44,Hilo,US,75.79,19.7297,-155.0900,Hilo Hawaiian Hotel
48,Buala,SB,84.29,-8.1450,159.5921,Maringe Lagoon Lodge
49,Micheweni,TZ,78.39,-4.9667,39.8333,
50,Cabo San Lucas,MX,77.61,22.8909,-109.9124,Hotel Tesoro Los Cabos
53,Airai,TL,82.06,-8.9266,125.4092,Juvinal Martin
56,Souillac,MU,77.38,-20.5167,57.5167,Shanti Maurice Resort & Spa
58,Butaritari,KI,82.89,3.0707,172.7902,Isles Sunset Lodge
73,Atuona,PF,77.67,-9.8000,-139.0333,Villa Enata
83,Georgetown,MY,84.15,5.4112,100.3354,Cititel Penang
87,Buchanan,LR,76.10,5.8808,-10.0467,Kamaneahn Hotel Inc
89,Victoria,HK,82.26,22.2855,114.1577,Mini Hotel Central
91,Alugan,PH,82.99,12.2188,125.4808,JM Lodge
97,Dano,BF,77.88,11.1500,-3.0667,Auberge Phenix32-Dano
103,Avarua,CK,75.25,-21.2078,-159.7750,Paradise Inn
105,Hithadhoo,MV,83.95,-0.6000,73.0833,Scoop Guest House
106,Salalah,OM,77.09,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
108,Honiara,SB,84.76,-9.4333,159.9500,Heritage Park Hotel
110,Catuday,PH,84.16,16.2923,119.8062,Benjie's Kubo & Cottages
114,Seddon,AU,83.21,-37.8068,144.8916,Footscray Motor Inn
118,Palasa,IN,82.44,18.7667,84.4167,Balaji tifen & meals veg & non veg hotel
123,Bandarbeyla,SO,78.48,9.4942,50.8122,JABIR HOTEL
125,Cayenne,GF,80.10,4.9333,-52.3333,Hôtel Le Dronmi
127,Rosario,AR,79.83,-32.9468,-60.6393,"Holiday Inn Rosario, an IHG Hotel"
128,Karratha,AU,87.42,-20.7377,116.8463,ibis Styles Karratha
137,Gamba,GA,75.52,-2.6500,10.0000,
140,Praia,CV,77.54,14.9215,-23.5087,LT Aparthotel
145,Alofi,NU,78.69,-19.0595,-169.9187,Taloa Heights
146,Bengkulu,ID,79.93,-3.8004,102.2655,Grage Hotel Bengkulu

In [43]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [44]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [47]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [48]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))